version: "3.9"
services:
  server:
    container_name: golang_server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "${PORT}:${PORT}"
    restart: always
    volumes:
      - .:/web/udrio
  postgres:
    container_name: udrio_postgres
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=udrio
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/data/udrio
  redis:
    container_name: udrio_redis
    image: redis:7-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - cache:/data
volumes:
  postgres-db:
    driver: local
  cache:
    driver: local
