version: "3.9"
services:
  server:
    container_name: golang_server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - .:/app
  postgres:
    container_name: udrio_postgres
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=udrio
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/data/udrio
    healthcheck:
      test: "exit 0"
volumes:
  postgres-db:
    driver: local
