version: "3.9"
services:
  server:
    container_name: golang_server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
    restart: always
    volumes:
      - .:/app
  postgres:
    container_name: udrio_postgres
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/data/udrio
    healthcheck:
      test: "exit 0"
volumes:
  postgres-db:
    driver: local
